apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders-service
        image: hello-world-server:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: orders-db
        - name: DB_PORT
          value: "5432"
