apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: yourregistry/payments-service:latest
        env:
        - name: DB_HOST
          value: auth-db
        - name: DB_PORT
          value: "5432"
