apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: yourregistry/auth-service:latest
        env:
        - name: DB_HOST
          value: auth-db
        - name: DB_PORT
          value: "5432"
